apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
spec:
  serviceName: mosquitto
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6.15-openssl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
        resources: {}
        volumeMounts:
          - name: mosquitto-config
            mountPath: mosquitto/config
      volumes: 
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
          
